In [1]:
pwd

'C:\\Users\\iibm'

In [2]:
print ("workshop on python")

workshop on python


In [3]:
print ('zhi')

zhi


In [4]:
print ('a\'a\'')

a'a'


In [8]:
print ('''a 'kahkashan' ''')

a 'kahkashan' 


In [9]:
print('''
data
science
zhi
''')


data
science
zhi



arithmetic operation

# Arithmetic operation

In [11]:
2+5

7

In [12]:
3+5

8

In [13]:
4//2

2

In [14]:
2e2

200.0

In [15]:
5*5+8*2

41

In [16]:
(5+5)*2

20

In [17]:
x=10
x

10

In [18]:
x=20

In [19]:
x

20

In [20]:
type(x)

int

In [21]:
print(type(x))

<class 'int'>


In [25]:
s='workshop'

In [26]:
s

'workshop'

# Slicing and Indexing

s[start:end:step]

In [27]:
s[:]

'workshop'

In [28]:
s[: :]

'workshop'

In [29]:
s[5]

'h'

In [30]:
s[:5]

'works'

In [31]:
s[3:]

'kshop'

In [32]:
s[: :2]

'wrso'

In [33]:
s[: :-1]

'pohskrow'

# Method

In [35]:
s=s.upper()

In [36]:
s

'WORKSHOP'

In [37]:
s.lower()

'workshop'

split

In [40]:
'data'.split()

['data']

In [41]:
'A B C D E'.split()

['A', 'B', 'C', 'D', 'E']

In [42]:
'A B C D E'.split('C')

['A B ', ' D E']

In [43]:
s.split('S')

['WORK', 'HOP']

In [44]:
name='Kahkashan'
marks=90

In [47]:
print(name+str(marks))

Kahkashan90


# Formating

In [48]:
print ('this is a % pen','ram')

this is a % pen ram


In [49]:
print('this is a %s pen %s ' %('ram', 'abc'))

this is a ram pen abc 


In [50]:
pwd

'C:\\Users\\iibm'

 # List

In [51]:
my_list=['A B C D E'.split()]

In [52]:
my_list

[['A', 'B', 'C', 'D', 'E']]

In [57]:
mylist=['a', 5, 5.3]

In [58]:
mylist


['a', 5, 5.3]

In [59]:
print(type(mylist))

<class 'list'>


# Slicing and Indexing

In [60]:
mylist[1]

5

In [61]:
mylist[0:3:1]

['a', 5, 5.3]

In [62]:
mylist[0:2]

['a', 5]

In [63]:
mylist[0:3:2]

['a', 5.3]

In [64]:
mylist*2

['a', 5, 5.3, 'a', 5, 5.3]

In [65]:
mylist=mylist + ['a']

In [66]:
mylist

['a', 5, 5.3, 'a']

# List Method

In [67]:
l=[1,2,3,4,5]

In [69]:
l

[1, 2, 3, 4, 5]

l.append('A B C' .split())

In [70]:
l

[1, 2, 3, 4, 5]

In [71]:
l.append('A B C' .split())

In [72]:
l

[1, 2, 3, 4, 5, ['A', 'B', 'C']]

In [73]:
l.append('A')

In [74]:
l

[1, 2, 3, 4, 5, ['A', 'B', 'C'], 'A']

In [75]:
print(l)

[1, 2, 3, 4, 5, ['A', 'B', 'C'], 'A']


In [76]:
list1=[1,2,3,4,5]

In [77]:
list1

[1, 2, 3, 4, 5]

In [78]:
print(list)

<class 'list'>


In [79]:
print(type(list))

<class 'type'>


In [81]:
list.append('a')
list

TypeError: descriptor 'append' for 'list' objects doesn't apply to a 'str' object

In [83]:
list1.append('a')
list1

[1, 2, 3, 4, 5, 'a', 'a']

In [84]:
list1.pop(2)

3

In [89]:
l1=[1,2,3]
l2=[4,5,6]
l3=[6,7,8]

In [90]:
matrix=[l1,l2,l3]

In [91]:
matrix

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]

In [92]:
type(matrix)

list

In [93]:
matrix[1] [0]

4

In [94]:
len(matrix)

3

# touple

In [95]:
t1=(1,2,3)

In [96]:
t1

(1, 2, 3)

In [97]:
type(t1)

tuple

In [98]:
print(type(t1))

<class 'tuple'>


In [99]:
t1

(1, 2, 3)

In [100]:
t1[2]='a'

TypeError: 'tuple' object does not support item assignment

In [101]:
l2=[1,2,3]

In [102]:
l2[2]=5

In [103]:
l2

[1, 2, 5]

In [104]:
t1[1]

2

In [107]:
t1[-1]

3

# Touple Method

In [106]:
t1.index(2)

1

In [108]:
t1.count(3)

1

# Dictionary

In [109]:
disc1={1:'a',2:'b',3:'c'}

In [110]:
disc1

{1: 'a', 2: 'b', 3: 'c'}

In [111]:
type(disc1)

dict

In [112]:
print(type(disc1))

<class 'dict'>


In [113]:
disc1[1]

'a'

In [114]:
disc1[2]

'b'

In [115]:
disc1[4]='ram'

In [116]:
disc1

{1: 'a', 2: 'b', 3: 'c', 4: 'ram'}

# Nested Dictionary

In [120]:
disc1={1: 'a',2: 'b','key1':{1: 'a',2: 'hello',3:'c'},3:'c'}

In [121]:
disc1

{1: 'a', 2: 'b', 'key1': {1: 'a', 2: 'hello', 3: 'c'}, 3: 'c'}

In [122]:
disc1['key1'][2][2]

'l'

In [123]:
disc1['key1'][2]

'hello'

# Method

In [124]:
disc1.keys()

dict_keys([1, 2, 'key1', 3])

In [126]:
disc1.values()

dict_values(['a', 'b', {1: 'a', 2: 'hello', 3: 'c'}, 'c'])

In [127]:
disc1.items()

dict_items([(1, 'a'), (2, 'b'), ('key1', {1: 'a', 2: 'hello', 3: 'c'}), (3, 'c')])

# set

# Unodered collection

In [128]:
x=set()

In [129]:
x

set()

In [130]:
set()

set()

In [131]:
print(type(x))

<class 'set'>


In [132]:
x.add(1)

In [133]:
x

{1}

In [134]:
list2=[1,2,3,1,2,3,2,2,3,4]

In [135]:
list2

[1, 2, 3, 1, 2, 3, 2, 2, 3, 4]

In [136]:
set(list2)

{1, 2, 3, 4}

### Boolean

In [139]:
True

True

In [140]:
False

False

In [141]:
None

In [143]:
list3=[1,2,[3,4,'goodbye']]

In [144]:
list3

[1, 2, [3, 4, 'goodbye']]

In [149]:
list3[2][2]='hello'

In [151]:
list3[2][2]='goodbye'

In [152]:
list3

[1, 2, [3, 4, 'goodbye']]

In [153]:
list5=[1,2,2,33,4,4,11,22,3,3,2]

In [154]:
list5

[1, 2, 2, 33, 4, 4, 11, 22, 3, 3, 2]

In [155]:
set(list5)

{1, 2, 3, 4, 11, 22, 33}

# Membership Operation

In [156]:
m='zhipatna'

In [157]:
m

'zhipatna'

In [158]:
'p' in m

True

In [159]:
't' not in m

False

In [160]:
x=100

In [161]:
y=100

In [162]:
x is y

True

In [163]:
x is not y

False

In [164]:
list1=[1,2,3]

In [165]:
list2=[1,2,3]

In [166]:
list1 is list2

False

In [167]:
list1==list2

True

# Numerical Python

In [168]:
import numpy as np

In [170]:
x=[1,2,3,4,5]
x

[1, 2, 3, 4, 5]

In [171]:
type(x)

list

In [173]:
y=np.array(x)

In [174]:
type(y)

numpy.ndarray

In [175]:
x2=(1,2,3,'NTELIT',3,4)

In [176]:
np.array(x2)

array(['1', '2', '3', 'NTELIT', '3', '4'], dtype='<U11')

# Linspace

In [179]:
np.linspace(start=0, stop=20, num=10, endpoint=False,retstep=True)

(array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.]), 2.0)

In [180]:
np.linspace(start=0, stop=20, num=10, endpoint=True,retstep=True)

(array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
        11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ]),
 2.2222222222222223)

# Arange

In [182]:
np.arange(start=0,stop=50,step=5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [183]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [185]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [186]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [187]:
np.arange()

TypeError: arange() missing required argument 'start' (pos 1)

# Create 3*3 Array

In [190]:
z=[[1,2,3],[4,5,6],[7,8,9]]

In [191]:
z

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [193]:
y=np.array(z)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [194]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [195]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [196]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Reshaping

In [197]:
x=np.array([0,1,2,3,4,5,6,7,8,9])

In [198]:
x #1*10 type

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Convert to 5*2

In [199]:
x.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [200]:
x.reshape((1,10))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [201]:
x.reshape((10,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [203]:
x.reshape((2,10))

ValueError: cannot reshape array of size 10 into shape (2,10)

# Sliceing

In [204]:
a = np.arange(10)

In [205]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [206]:
s = slice(2,7)

In [207]:
a[s]

array([2, 3, 4, 5, 6])

In [208]:
s1=slice(2,7,2)

In [209]:
a[s1]

array([2, 4, 6])

In [210]:
a[2:7]

array([2, 3, 4, 5, 6])

In [211]:
a[2:7:2]

array([2, 4, 6])

# Random Number Generation

In [212]:
np.random.rand(5)

array([0.71881264, 0.79848734, 0.58398252, 0.33209663, 0.35132646])

In [213]:
np.random.rand(5)

array([0.21211403, 0.87222   , 0.56785678, 0.9579039 , 0.60672934])

# Normal Distribution

In [214]:
np.random.rand(5,4)

array([[0.85179249, 0.70189162, 0.52747049, 0.64207457],
       [0.09938594, 0.40348155, 0.12968364, 0.50794759],
       [0.69754036, 0.97721713, 0.04608199, 0.54923936],
       [0.93527119, 0.87961021, 0.63661032, 0.02237094],
       [0.43051122, 0.80733274, 0.6830567 , 0.47537542]])

# Randint

In [215]:
np.random.randint(low=0,high=100)

62

In [216]:
# 4 digit Random Number
np.random.randint(low=1000,high=9999)

4349

In [217]:
np.random.randint(low=1000,high=9999,size=10)

array([6364, 4532, 4061, 9816, 8871, 3083, 4595, 2231, 6085, 2659])

# Seed

In [220]:
np.random.seed(23)
np.random.rand(4)

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584])

In [221]:
np.random.seed(23)
np.random.rand(4)
            

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584])