# Broadcasting

In [ ]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr/10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [5]:
l1 =[0,1,2,3,4,5,6,7,8,9]

In [6]:
l1[1]/10

0.1

In [7]:
arr*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [8]:
arr-1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [9]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [10]:
arr[arr>5]

array([6, 7, 8, 9])

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr1=arr[0:6]

In [14]:
arr1

array([0, 1, 2, 3, 4, 5])

In [15]:
arr[:5]

array([0, 1, 2, 3, 4])

In [16]:
arr[:4]

array([0, 1, 2, 3])

In [17]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr1[:]

array([0, 1, 2, 3, 4, 5])

In [19]:
arr1

array([0, 1, 2, 3, 4, 5])

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# copy of an array

In [23]:
arr2 = arr.copy()

In [24]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr2[:]=1000

In [26]:
arr2

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Python list Vs Numpy array

In [28]:
size = 1000
x = range (size)
y = range (size)

In [29]:
%%timeit
[x[i]*y[i] for i in range(size)]

209 µs ± 3.11 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [30]:
x1 = np.arange(size)
y1 = np.arange(size)

In [31]:
%%timeit
x1*y1

1.24 µs ± 9.24 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Insert

In [38]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
b1 = np.insert(b,1,[15,16,17],axis=0)


In [41]:
 np.insert(b,1,[15,16,17],axis=1)

array([[ 1, 15,  2,  3],
       [ 4, 16,  5,  6],
       [ 7, 17,  8,  9]])

In [42]:
b1

array([[ 1,  2,  3],
       [15, 16, 17],
       [ 4,  5,  6],
       [ 7,  8,  9]])

# 

# Matrix

In [48]:
x = np.matrix('1,2,3;4,5,6;7,8,9')

In [49]:
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [50]:
x[2,1]= -7

In [51]:
x

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7, -7,  9]])

In [52]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [53]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
arr[2,1] = -7

In [59]:
np.insert(arr,2,2)

array([ 1,  2,  2,  3,  4,  5,  6,  7, -7,  9])

In [60]:
x*x

matrix([[ 30,  -9,  42],
        [ 66,  -9,  96],
        [ 42, -84,  60]])

In [61]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 49, 81]])

In [62]:
arr@arr

array([[ 30,  -9,  42],
       [ 66,  -9,  96],
       [ 42, -84,  60]])

# Storage in File

In [63]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [65]:
np.savetxt('a.txt',arr)

In [67]:
np.savetxt('a.txt',arr,delimiter=',')

In [68]:
np.loadtxt('a.txt',delimiter=',')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7., -7.,  9.]])

In [70]:
np.save('data.npy',arr)

In [72]:
np.load('data.npy')

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [74]:
a = np.arange(10)

In [75]:
np.savez('both.npz',arr,a)

In [76]:
z = np.load('both.npz')

In [77]:
z.files

['arr_0', 'arr_1']

In [78]:
z[z.files[0]]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, -7,  9]])

In [79]:
z[z.files[1]]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Pandas

In [80]:
import pandas as pd
import numpy as np

# Using list

In [81]:
my_list = [100,200,300,400,500]

In [82]:
x = pd.Series(my_list,index=['A','B','C','D','E'])

In [83]:
x

A    100
B    200
C    300
D    400
E    500
dtype: int64

In [85]:
type(x)

pandas.core.series.Series

# Using numpy Array

In [86]:
arr = np.array(my_list)
arr

array([100, 200, 300, 400, 500])

In [87]:
'A B C D E' .split()

['A', 'B', 'C', 'D', 'E']

In [88]:
pd.Series(arr,'A B C D E'.split())

A    100
B    200
C    300
D    400
E    500
dtype: int32

# Using Dictionaries

In [90]:
dict1={'A':100,'B':200,'C':300}

In [91]:
z1 = pd.Series(dict1)
z1

A    100
B    200
C    300
dtype: int64

In [94]:
z2 = pd.Series([10,20,30,40],'A B C D '.split())

In [95]:
z2

A    10
B    20
C    30
D    40
dtype: int64

In [96]:
z1+z2

A    110.0
B    220.0
C    330.0
D      NaN
dtype: float64

# Slicing in series
# z2

In [98]:
z2['A':'C']

A    10
B    20
C    30
dtype: int64

# .loc & .iloc Function

In [99]:
z2.loc['A':'C']

A    10
B    20
C    30
dtype: int64

In [100]:
z2.iloc[0:3]

A    10
B    20
C    30
dtype: int64

In [101]:
z = pd.Series({100:'a',200:'b',300:'c'})

In [102]:
z

100    a
200    b
300    c
dtype: object

In [103]:
z[0]

KeyError: 0

In [104]:
z.iloc[0]

'a'

# Operation

In [105]:
z1

A    100
B    200
C    300
dtype: int64

In [106]:
z1>100

A    False
B     True
C     True
dtype: bool

In [107]:
z1<200

A     True
B    False
C    False
dtype: bool

# Broadcasting

In [108]:
z1+300

A    400
B    500
C    600
dtype: int64

# Odering

In [109]:
z2

A    10
B    20
C    30
D    40
dtype: int64

In [110]:
z2.sort_values(ascending=False)

D    40
C    30
B    20
A    10
dtype: int64

In [111]:
z2

A    10
B    20
C    30
D    40
dtype: int64

In [113]:
z2.sort_values(ascending=False,inplace=True)

In [114]:
z2

D    40
C    30
B    20
A    10
dtype: int64

# Aggregration on Series

In [115]:
z2

D    40
C    30
B    20
A    10
dtype: int64

In [116]:
z2.min()

10

In [117]:
z2.max()

40

In [118]:
z2.idxmax()

'D'

# Data Frame

In [119]:
rand_mat = np.random.randn(5,4)

In [120]:
rand_mat

array([[-1.1905777 , -1.72954389,  0.79978695,  0.33508489],
       [-0.69419662,  0.46322229, -1.12200631,  0.04245657],
       [-1.06604761, -0.76418852, -1.33352908,  0.53179716],
       [-0.71628079,  0.3866858 , -1.04392176,  2.15105371],
       [ 1.16065935,  0.48331546, -0.42116303, -1.87671385]])

In [123]:
df = pd.DataFrame(data=rand_mat, index = 'A B C D E'.split(),columns = 'W X Y Z'.split())

In [124]:
df

W         X         Y         Z
A -1.190578 -1.729544  0.799787  0.335085
B -0.694197  0.463222 -1.122006  0.042457
C -1.066048 -0.764189 -1.333529  0.531797
D -0.716281  0.386686 -1.043922  2.151054
E  1.160659  0.483315 -0.421163 -1.876714

In [125]:
type(df)

pandas.core.frame.DataFrame

In [126]:
df['W']

A   -1.190578
B   -0.694197
C   -1.066048
D   -0.716281
E    1.160659
Name: W, dtype: float64

In [127]:
type(df['W'])

pandas.core.series.Series

# Selection and Indexing

In [128]:
df.loc['A']

W   -1.190578
X   -1.729544
Y    0.799787
Z    0.335085
Name: A, dtype: float64

In [129]:
df[['W','Z']]

W         Z
A -1.190578  0.335085
B -0.694197  0.042457
C -1.066048  0.531797
D -0.716281  2.151054
E  1.160659 -1.876714

# Add a New column

In [130]:
df['New'] = df['W'] + df['Y']

In [131]:
df

W         X         Y         Z       New
A -1.190578 -1.729544  0.799787  0.335085 -0.390791
B -0.694197  0.463222 -1.122006  0.042457 -1.816203
C -1.066048 -0.764189 -1.333529  0.531797 -2.399577
D -0.716281  0.386686 -1.043922  2.151054 -1.760203
E  1.160659  0.483315 -0.421163 -1.876714  0.739496

In [132]:
df.drop('New',axis=1)

W         X         Y         Z
A -1.190578 -1.729544  0.799787  0.335085
B -0.694197  0.463222 -1.122006  0.042457
C -1.066048 -0.764189 -1.333529  0.531797
D -0.716281  0.386686 -1.043922  2.151054
E  1.160659  0.483315 -0.421163 -1.876714

In [133]:
df.drop('New',axis=1,inplace=True)

In [134]:
df

W         X         Y         Z
A -1.190578 -1.729544  0.799787  0.335085
B -0.694197  0.463222 -1.122006  0.042457
C -1.066048 -0.764189 -1.333529  0.531797
D -0.716281  0.386686 -1.043922  2.151054
E  1.160659  0.483315 -0.421163 -1.876714

# Add a new row

In [135]:
df.loc['F'] = df.loc['A'] + df.loc['C']
df

W         X         Y         Z
A -1.190578 -1.729544  0.799787  0.335085
B -0.694197  0.463222 -1.122006  0.042457
C -1.066048 -0.764189 -1.333529  0.531797
D -0.716281  0.386686 -1.043922  2.151054
E  1.160659  0.483315 -0.421163 -1.876714
F -2.256625 -2.493732 -0.533742  0.866882

In [136]:
df.drop('F',axis=0,inplace=True)

In [137]:
df

W         X         Y         Z
A -1.190578 -1.729544  0.799787  0.335085
B -0.694197  0.463222 -1.122006  0.042457
C -1.066048 -0.764189 -1.333529  0.531797
D -0.716281  0.386686 -1.043922  2.151054
E  1.160659  0.483315 -0.421163 -1.876714

In [138]:
df['X']['C']

-0.7641885193964616

In [139]:
df.loc['C']['X']

-0.7641885193964616

# Data Input & Output

In [141]:
pd.read_csv('example.csv')



Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2021                     Level 1                99999   
1      2021                     Level 1                99999   
2      2021                     Level 1                99999   
3      2021                     Level 1                99999   
4      2021                     Level 1                99999   
...     ...                         ...                  ...   
41710  2013                     Level 3                 ZZ11   
41711  2013                     Level 3                 ZZ11   
41712  2013                     Level 3                 ZZ11   
41713  2013                     Level 3                 ZZ11   
41714  2013                     Level 3                 ZZ11   

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01   
1                  All industries  Dollars (millions)           H04   
2                  All industries  Dollars (millions)           H05   
3                  All industries  Dollars (millions)           H07   
4                  All industries  Dollars (millions)           H08   
...                           ...                 ...           ...   
41710  Food product manufacturing          Percentage           H37   
41711  Food product manufacturing          Percentage           H38   
41712  Food product manufacturing          Percentage           H39   
41713  Food product manufacturing          Percentage           H40   
41714  Food product manufacturing          Percentage           H41   

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance   
1      Sales, government funding, grants and subsidies  Financial performance   
2                    Interest, dividends and donations  Financial performance   
3                                 Non-operating income  Financial performance   
4                                    Total expenditure  Financial performance   
...                                                ...                    ...   
41710                                      Quick ratio       Financial ratios   
41711              Margin on sales of goods for resale       Financial ratios   
41712                                 Return on equity       Financial ratios   
41713                           Return on total assets       Financial ratios   
41714                            Liabilities structure       Financial ratios   

         Value                             Industry_code_ANZSIC06  
0      757,504  ANZSIC06 divisions A-S (excluding classes K633...  
1      674,890  ANZSIC06 divisions A-S (excluding classes K633...  
2       49,593  ANZSIC06 divisions A-S (excluding classes K633...  
3       33,020  ANZSIC06 divisions A-S (excluding classes K633...  
4      654,404  ANZSIC06 divisions A-S (excluding classes K633...  
...        ...                                                ...  
41710       52  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
41711       40  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
41712       12  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
41713        5  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
41714       46  ANZSIC06 groups C111, C112, C113, C114, C115, ...  

[41715 rows x 10 columns]

# Statics function


In [143]:
import numpy as np

In [144]:
x = np.array([[1,2,3,],[2,4,6],[90,100,50]])

In [145]:
x

array([[  1,   2,   3],
       [  2,   4,   6],
       [ 90, 100,  50]])

In [146]:
np.amin(x)

1

In [147]:
np.amax(x)

100

In [148]:
np.amin(x, axis=1)

array([ 1,  2, 50])

In [149]:
np.amin(x, axis=0)

array([1, 2, 3])

In [150]:
np.amax(x, axis=0)

array([ 90, 100,  50])

In [151]:
np.amax(x, axis=1)

array([  3,   6, 100])

In [152]:
x

array([[  1,   2,   3],
       [  2,   4,   6],
       [ 90, 100,  50]])

In [153]:
np.average(x)

28.666666666666668

# Weighted Average

In [154]:
w=[1,2,3]

In [155]:
np.average(x, weights=w, axis=0)

array([45.83333333, 51.66666667, 27.5       ])

In [156]:
np.average(x, weights=w, axis=1)

array([ 2.33333333,  4.66666667, 73.33333333])

In [157]:
np.mean(x)

28.666666666666668

In [158]:
np.mean(x[0])

2.0

In [159]:
np.mean(x[1])

4.0

In [160]:
np.mean(x[2])

80.0

In [161]:
np.mean(x, axis=0)

array([31.        , 35.33333333, 19.66666667])

In [162]:
np.mean(x, axis=1)

array([ 2.,  4., 80.])

In [163]:
np.median(x)

4.0

In [164]:
np.median(x, axis=0)

array([2., 4., 6.])

In [167]:
np.var(x)

1474.888888888889

In [165]:
np.std(x)

38.4042821686448